#!/bin/bash
#
# Download and install latest compiled GAMADV-XTD3
#
# You MUST edit the YourHomeDir variable below in the three places, and maybe also the actual gamadv-xtd3 dir.
# The reason for hardcoding the program dir is because you can have several separate GAM versions installed at the same time, and may not want to update them all.

if /home/YourHomeDir/gamadv-xtd3/gam version checkrc; then
        echo $? #This line isn't necessary. I have it just to see the error code from the checkrc command. 0 means TRUE and that the versions match.
        echo "You are using the current version!"
        exit
else
        echo $? #This line isn't necessary. Just like the one above.
        echo "There's a newer version of GAMADV-XTD3. Downloading it now."
        bash <(curl -s -S -L https://git.io/fhZWP) -l -d /home/YourHomeDir
        more /home/YourHomeDir/gamadv-xtd3/GamUpdate.txt #This line opens the GamUpdate.txt file, so I can see what new features or bugfixes has been added.
        #If you are to fully automate the updating, you need to disable this line completely.
fi
